### ISSUE TITLE
Alternate I exists in caps but not Small Caps

### ISSUE THREAD

**Issue by frankrolf** [adobe-fonts/source-sans#190]
The capital `I` has a slab-serif alternate, `I.a`. The same kind of alternate does not exist in the Small Caps – which may or may not be a conscious decision.

**Comment by StatisticalProgrammer** [comment]
Please make the slab-serif (serif?) capital **I** the default, so that even isolated it can be easily distinguished from lower-case ell and one (**l** and **1**),  in the spirit of the legibility-standard DIN 1450. 

In Open Office, this is denoted Source Sans 3:ss01. 

(Thank you for the superb font, especially its ell.)

Bigelow, Charles. ``Oh, oh, zero!''. TUGboat 34, no. 2 (2013): 168-181. https://www.tug.org/TUGboat/tb34-2/tb107bigelow-zero.pdf

**Comment by pauldhunt** [comment]
@StatisticalProgrammer Thanks for your input, however I feel that the current designs are suitably differentiated by the tail + ascender height on l (⬇️L) and the foot on 1. I feel no need to follow the DIN standard as this typeface is not trying to be DIN.

**Comment by StatisticalProgrammer** [comment]
Thank you, @pauldhunt, for the informative reply. 

While on the topic of small caps, I alert you that the **regular** font's small caps does not work for my LaTeX configuration (fontspec, TeX Studio, MikTeX) on Windows 10, but the small caps work fine for the bold. I used the Display-Regular font to create the pdf file form which this was snipped:
 
![image](https://user-images.githubusercontent.com/16743568/107742418-471dbb80-6d0f-11eb-8f8f-ad0a36427190.png)

Thanks again for the great family of typefaces.

**Comment by KrasnayaPloshchad** [comment]
This character is encoded in U+A7AE (Ɪ).

**Comment by StatisticalProgrammer** [comment]
Source Sans has in its fractional numerals the 1 without the lower serif, according to this Youtube video from fontribute (TypeThursday's Thomas Jockin, with Erin McLaughlin):

> Exploring fonts for User Interfaces: Fontribute of Source Sans and Fira Sans
> [https://www.youtube.com/watch?v=pK0KPd481-M](https://www.youtube.com/watch?v=pK0KPd481-M)

As this is a design choice consistent with the fractions (rather than a semantic error), The above graphic should change the red 1 to a blue.

**Comment by miguelsousa** [comment]
@StatisticalProgrammer I've wrapped the LaTeX code above with backticks to make it a [fenced code block with syntax highlighting](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).
