### ISSUE TITLE
Fonts Name Change: ❛Source Sans Pro❜ to become ❛Source Sans 3❜

### ISSUE THREAD

**Issue by pauldhunt** [adobe-fonts/source-sans#192]
This note is to give a heads up to Source Sans users that the next updated version of the fonts changes the font names to reflect the major version number. This will lead to backward compatibility issues for older implementations. If you use the most up-to-date improvements in the new version, you will need to update your references to reflect this name change.

**Comment by dmcknight26** [comment]
Any idea when the release will be out?

**Comment by fitojb** [comment]
Well, I guess this means the end of LibreOffice’s bundling (and automatic upgrading) of the Source font families. It’s easier to just let users find them on their own and avoid situations where we upgrade them in a new release and suddenly their documents break, and blame the project for it. This is such a silly move that I can’t wrap my head around it. Why is there a Version field, then? It’s as if “2020” were an official part of the trademarked “Adobe InDesign” name. Fonts may be software but this crosses the line. “Pro” was perfectly fine in its ambiguousness—its scope is mostly meaningless for end users and, thus, acceptable for stable naming!

**Comment by pauldhunt** [comment]
[Source Sans 3 version 3.028](https://github.com/adobe-fonts/source-sans-pro/releases/tag/3.028R) is out now.

**Comment by SL-Lee** [comment]
Please revert this change. Font *names* are not meant to be used for versioning, and as @fitojb already mentioned, that's what the *version field* is for. Having to update every setting across multiple applications where "Source Sans Pro" is used is a huge hassle, and this amount of effort just for a breaking font name change should be unnecessary.

**Comment by elcste** [comment]
I've also found that some applications don't seem to be able to handle a font with a number in the name.

- Chrome's setting pages specify Roboto then the system font, but it's not quoted, so with Source Sans 3 the CSS is invalid and the page gets shown in the browser default font, Times or whatever it's been set to.

- DuckDuckGo's custom font option won't work with a font with a number in the name like Source Sans 3.

Clearly neither of these are Source Sans's bug – and they also seem to happen with a font with punctuation in the name, like "[M+ 1c](https://mplus-fonts.osdn.jp/about-en.html)" ­– but they never came up with the name "Source Sans Pro". I will report the Chome issue at least so hopefully it will be fixed, but who knows what other programs out there have this kind of of problem. Because of this, I'd even prefer the name "Source Sans", but reverting to "Source Sans Pro" is still my preference as well.

**Comment by twardoch** [comment]
If the font changes metrics or the design changes visibly, then a change in
the name should indeed happen. Otherwise existing documents reflow, which
is bad for many users.

**Comment by SL-Lee** [comment]
@twardoch As far as I can tell, the main driving force of the renaming of "Source Sans Pro" to "Source Sans 3" was *not* due to change in the metrics, nor was it due to a considerable change in design\[1]. Rather, it was because of [converting the UFO masters to version 3](https://github.com/adobe-fonts/source-sans-pro/issues/148), which seems more like a developer-oriented change than anything else. To the end-user, this is meaningless anyway — most of them will not even know how fonts are built. Thus, I still believe that the change in the font name will do more harm than good to the end-user, as this font name change will require end-users to update every setting where "Source Sans Pro" was used.

---

[1]: If this is the reasoning for a change in the font name, then what about Roboto? Roboto underwent a major design overhaul in 2014, which certainly fits your guidelines of changed font metrics *and* font design, but Google stuck with the name "Roboto". There isn't any "Roboto 2" or whatsoever.

**Comment by kiwi0fruit** [comment]
@pauldhunt But why this name change?

**Comment by kiwi0fruit** [comment]
By the way on Adobe site there is only "Source Sans" font: https://fonts.adobe.com/fonts/source-sans (without "Pro"). Same is for Serif and Code.

**Comment by beschulz** [comment]
What a PITA!

**Comment by dixius99** [comment]
Isn't [Source Serif Pro](https://github.com/adobe-fonts/source-serif-pro) on version 3, and it's name _didn't_ change? At very least this seems really inconsistent. I now have Source Code Pro, Source Serif Pro, and Source Sans 3.

(please don't interpret this comment as a request to change the name of Source Serif Pro)

**Comment by timc3** [comment]
Is it a different font to Source Sans Pro? This is ridiculous.

**Comment by dixius99** [comment]
Just an update that Source Serif Pro has been renamed to Source Serif 4. So my comment above is no longer valid.

We now have Source Serif 4, Source Sans 3, and Source Code Pro.

**Comment by pauldhunt** [comment]
@timc3 a font is a piece of software and as the software is quite different from the previous major version, there is no reason not to reflect this in the name of the software. Software is not always backward compatible and backward compatibility is not something I want to be held accountable for with this project, hence the break in continuity with the software name.
