### ISSUE TITLE
Request to add 4 additional IPA characters: ʛ, ⱱ, ǀ, ǁ (was: International Phonetic Alphabet support)

### ISSUE THREAD

**Issue by Linguistx** [adobe-fonts/source-sans#215]
Love this font. It almost has all IPA symbols but I noticed four missing glyphs (only tested Regular weight)

- ʛ
- ⱱ
- ǀ
- ǁ 

Are there any plans to add these? It's always great to have more fonts that support IPA, because there's only a handful that do.

Reference: https://www.phon.ucl.ac.uk/home/wells/ipa-unicode.htm

**Comment by projectshifter** [comment]
Has this actually been addressed in the source files? The latest development build (3.38) still doesn’t support these. Also missing are:

* U+02D2 through U+02D7, the standalone forms of the relative articulation diacritics,
* U+02E5 through U+02E9, the official tone letters which require OpenType substitutions to render properly,
* U+025D, the conventional transcription of the vowel in American English _nurse_ or _term_, 
* U+0296 and U+0297, obsolete symbols for clicks which can still be found in the literature,
* and a lot of superscript modifier letters, which can indicate either secondary articulation or optional sounds; U+1D51, U+1D5D, U+1DAE and U+02B4 are some of the most common.

**Comment by projectshifter** [comment]
I noticed that when typing affricates with a tie bar ([t͡s t͡ʃ] etc.), they convert to ligatures ([ʦ ʧ] etc.). It’s true that digraphs with a tie bar and ligatures are functionally identical within IPA, but they’re still different glyph sequences and should render differently.

**Comment by projectshifter** [comment]
Will do. Thanks for the information though.

**Comment by moyogo** [comment]
Any feature that replaces the ligature tie sequences with the ligature symbols is wrong.

The IPA deprecated the ligature symbols ʣ ʥ ʤ ʨ ʦ ʧ in 1989 and recommended the use of ligature ties, because many more sounds can be represented with ties rather than having to create new ligature symbols. These ligature symbols should not be used anymore but are still very common in documents.
The official IPA way to represent those affricate consonants or doubly articulated segments is with the top or bottom ligature ties when there's ambiguity with a sequence of consonant or no ties at all when there is no ambiguity:
- d͡z d͡ʑ d͡ʒ t͡ɕ t͡s t͡ʃ k͡x k͡p ...
- d͜z d͜ʑ d͜ʒ t͜ɕ t͜s t͜ʃ k͜x k͜p ...
- dz dʑ dʒ tɕ ts tʃ kx kp ...

See International Phonetic Association, ”Report on the 1989 Kiel Convention“, *Journal of the International Phonetic Association*, 19 (2),‎ 1989
<img width="986" alt="image" src="https://user-images.githubusercontent.com/1923747/119093844-264cbc80-ba08-11eb-9542-2e30691db9a1.png">

See also International Phonetic Association, *Handbook of the International Phonetic Association : a guide to the use of the International Phonetic Alphabet*, Cambridge University Press, 1999
<img width="615" alt="image" src="https://user-images.githubusercontent.com/1923747/119094033-63b14a00-ba08-11eb-85bf-4c57477a2225.png">

It makes no sense to have any ligature feature substitute the official symbols with the obsolete forms.
If someone wants to use the obsolete symbols, they can and should use their characters.
