### ISSUE TITLE
Wrong 'д' glyph in Bulgarian Cyrillic

### ISSUE THREAD

**Issue by dkoutevska** [adobe-fonts/source-sans#226]
Hello.
I'm using this font for web, and more specifically the Bulgarian Cyrillic features (lang="bg"). 

BUG:
I've noticed that the lowercase `д` glyph is not the correct one for Bulgarian Cyrillic.
It's rendering the `uni0434.a`, but the correct one  is `uni0434.c`:
<img width="933" alt="Screenshot at Jul 13 12-42-26" src="https://user-images.githubusercontent.com/16247048/125432762-4a52c510-3f22-4677-bc0a-44680282a0b4.png">

Two more questions: 
1. The `.woff` formats have a weird extension, it's `.otf.woff` or `.ttf.woff` is this normal or did something mess up in the build?
2. The Bulgarian Cyrillic is rendering only when the src for my @font-face is `.otf`. If I add `.ttf` as src, it stops rendering the correct glyphs for Bulgarian and instead renders the Russian ones.  Is this a normal behaviour?

My knowledge of fonts is not extensive, so any info is appreciated.
Thank you!

**Comment by frankrolf** [comment]
As I am reading the feature code here, I assume the roof-shaped д was chosen deliberately:
https://github.com/adobe-fonts/source-sans/blob/master/Roman/locl_cyrl.fea#L6-L11
https://github.com/adobe-fonts/source-sans/blob/master/familyGSUB.fea#L1356-L1397

To get the g-shaped д, use Stylistic Set 7 or cv14 (e.g. `font-feature-settings: "ss07";`)

<img width="1066" alt="Screen Shot 2021-07-13 at 15 41 07" src="https://user-images.githubusercontent.com/2049645/125462178-ac627a3c-8e85-4e6e-a182-1c6683487fa8.png">

Answers to misc questions:
1. Different outline formats (OTF/TTF) exist, with different technical attributes. One or the other may be better suited for a given application. Since WOFFs just re-package font binaries, the extensions reflect this.
2. The substitution of Bulgarian Cyrillic should not depend on the differences between TTF/OTF font formats. In fact, the parts responsible for the OT glyph substitution are the same across both formats. What does however matter is the choice of browser – Chrome does support applying the locl feature via `lang="bg"`, Safari does not.
The @font-face declaration can become a bit complicated, make sure you follow this example:
https://github.com/adobe-fonts/source-sans/blob/release/source-sans-3.css#L6-L7

Hope this helps!

**Comment by dkoutevska** [comment]
Thank you for the fast response @frankrolf ! :)
