### ISSUE TITLE
Non-alternative greek uppercase forms not accessible

### ISSUE THREAD

**Issue by SirPL** [adobe-fonts/source-sans#238]
Hi.
I have problem with greek capitals. Even though regular forms of capital letters (i.e. reverse-V-shaped lambda) are shown by DTP apps (see yellow highlight), their variants (see red letters) are enabled by default _and_ I see no way to turn those variants off.

I am using non-variable font, version 3.046.

I checked the font in Affinity Publisher and Adobe InDesign (CS6) and the issue occurs in both applications.

![image](https://user-images.githubusercontent.com/11311649/158322115-d714686f-a404-4d64-96bc-8f545f4f3ec0.png)

**Comment by frankrolf** [comment]
I am confirming this behavior in ID 17, see here:
<img width="793" alt="Screen Shot 2022-03-15 at 11 38 50" src="https://user-images.githubusercontent.com/2049645/158360249-c9bfd85e-26cb-4be2-9d3c-766d899bfd88.png">

The reason for this is that Greek is substituted by “Greek for IPA” for any language but Greek:
https://github.com/adobe-fonts/source-sans/blob/master/familyGSUB.fea#L1483-L1485

I don’t know what the reason is for this approach, but it may indicate an issue with the `locl` features.
@pauldhunt will know more.

A workaround would be setting Greek language for the text you’re entering:
<img width="782" alt="Screen Shot 2022-03-15 at 11 38 38" src="https://user-images.githubusercontent.com/2049645/158360669-bea7fa86-fa61-4aa0-9870-763da8f3cf0e.png">

**Comment by pauldhunt** [comment]
Just a point of clarification on what @frankrolf has already said: the forms you are seeing are the Latin script variants of Greek characters. These are substituted when using Latin script languages to accommodate not only for IPA but for American Indigenous languages as well. 
Setting the language to something other than a language that is written in Latin script will give you the default Greek forms, ie changing the language to Russian or Arabic will display the expected Greek forms. These forms are intended only for Latin typography and thus substitutes the latinized forms.

**Comment by SirPL** [comment]
@pauldhunt - thank you for explanation.
I have to say this approach is quite... unusual.

I faced the issue when I tried to describe "Γ-distribution". I would argue that _Γ_ in this context is a Greek word :) Personally I would expect IPA alternatives to be turned on when specific Indigenous language is used.

**Comment by pauldhunt** [comment]
@SirPL  Unfortunately, indigenous orthographies are not as well supported as Greek in Unicode nor in the OpenType spec, so this particular feature is meant to provide cutting-edge support where proper standards support is lacking. Luckily, Greek language tagging is well-supported in many popular environments so the workaround of tagging text as Greek should work almost everywhere, even if it does subvert common expectations.

**Comment by frankrolf** [comment]
I can’t help but think that this approach will be more confusing but helpful.
Greek letters are not just used for the Greek language, but especially (and heavily) in scientific context – I don’t think we expect users to change language tagging when using these symbols?

**Comment by georgd** [comment]
This is a very interesting issue. "Western" users (and I am to be considered one of them) suddenly are experiencing what speakers of less privileged languages are experiencing every day — jumping through multiple loops in order to achieve acceptable output in their mothertongue due to deficient language support.

I support not to change the default behaviour because each language should easily be written. But I agree with @frankrolf that switching language tags to indicate scientific use of a letter isn't appropriate. I'd rather go with a switch implemented in, say,  ssXX, to indicate which Greek glyph set to use. N.b. this, too, is only a workaround to the disadvantage of less privileged languages as scientific expressions might pose additional difficulties to them.

**Comment by pauldhunt** [comment]
@frankrolf Confusing vs Helpful from whose perspective? I don’t typically think of Source Sans as a mathematics font. If someone were to use the font for serious mathematics settings, they would probably want to set the script to `math` or set the language tagging for equations to ‘no langauge’. Doing either of these things, again, will cause the Greek forms to display their default forms. Only tagging the text as a language using Latin script will reveal the latin-specific forms. 
So far, I view this issue as a minor inconvenience for mathematicians with some very simple work-arounds weighed against providing better language support for language communities that otherwise would have a very hard time getting their orthographies to work in typesetting applications. 
Again, this may be confusing for a few math typesetters, whom I would assume would have a very good handle on typographic systems and used to tweaking options to get their desired settings versus the indigenous language support is meant to help people who may be challenged with literacy in English and/or their own language and the inclusion of indigenous orthographies in Source Sans is intended to act as a support in the preservation and reclamation of indigenous languages by supporting their orthographies out of the box and removing technical barriers as much as possible.
For example, in InDesign to get the default Greek forms one can either 1) unset the language tagging, or 2) set the language tagging to Greek. The former should probably be done for mathematical equations, the latter for actual Greek text. If the situation was reversed and required language tagging for indigenous orthographies, the user would be required to find language dictionaries to add to InDesign that may or may not exist, they would have to install these properly following arcane instructions in English. Even after doing this InDesign may not actually apply the language features if it doesn’t recognize the latest OpenType language tagging for indigenous orthographies.
AFAICT, the way I have set up the font is the only way that will actually support indigenous orthographies otherwise ignored by Unicode and software developers up to this time. In the future, if the proper characters are added to Unicode, I would feel comfortable about reverting the current behavior to show expected Greek letter forms even when the typesetter is careless and not mindful of language tagging. However, I still do believe that it is appropriate to swap out Latinized forms in languages that use Latin script so I still see this as a non-issue and my choice here as entirely appropriate unless actual use cases are documented that show that this is not appropriate. If you come to this page and you feel you are facing one of those cases, please log it below.

**Comment by pauldhunt** [comment]
@SirPL you said:

 tried to describe

> "Γ-distribution". I would argue that Γ in this context is a Greek word…

Did you mean to say: ‘Γ in this context _isn’t_ a Greek word’? I just wanted to clarify.

**Comment by georgd** [comment]
> @SirPL you said:
> 
>  tried to describe
> 
> > "Γ-distribution". I would argue that Γ in this context is a Greek word…
> 
> Did you mean to say: ‘Γ in this context _isn’t_ a Greek word’? I just wanted to clarify.
>  
>  

At least, when writing in German, it is considered a foreign word but you wouldn't switch language context for it.

**Comment by pauldhunt** [comment]
>you wouldn't switch language context for it.

_I_ would, and in fact, I do set up specific character styles for language-specific words when putting together my own InDesign documents so that foreign words are italicized and language marked so as to show up properly when checking spelling in a document, but I guess this is personal habit and preference that varies from typographer to typographer.

**Comment by georgd** [comment]
Would you really switch language context to Greek for the words _schema_ and _typography_? They belong to the same class of foreign words as _gamma_.

**Comment by pauldhunt** [comment]
@georgd now we’re talking about something entirely different: while the etymology for the words schema, typography, and gamma is Greek, they have been fully incorporated into English for some time. However, the Greek letter Γ has not. Googling for "Γ-distribution" returns results with the phrase "Gamma distribution" with only one hit in the first page of results actually using the Greek letter. So if we are talking about subverting expectations, perhaps using "Γ-distribution" instead of "Gamma distribution" also breaks expectations that the Greek letter name be spelled out in Latin script? Using Google Trends shows that there are virtually no searches for the term "Γ-distribution": https://trends.google.com/trends/explore?q=%22%CE%93-distribution%22,%22Gamma%20distribution%22
