### ISSUE TITLE
Missing medium weight

### ISSUE THREAD

**Issue by huupoke12** [adobe-fonts/source-sans#253]
Hi, I see that there is no medium weight font in this typeface and also https://github.com/adobe-fonts/source-serif.
Please consider generating medium weight, since it is still being widely used.

**Comment by frankrolf** [comment]
The weight range for Source Sans (and also Source Serif) has been considered so that the styles work together harmoniously. While it is true that many typefaces contain a Medium weight, it would not make much sense to wedge one in between Regular and Semibold – there would not be enough weight difference to make that Medium be a good style for emphasis.

But – you’re in luck! The variable font gives you the possibility to choose any weight you desire.

**Comment by pauldhunt** [comment]
I will consider this for future releases.

**Comment by pauldhunt** [comment]
Medium weight added in version 3.052.

**Comment by pauldhunt** [comment]
This feature is deployed in the [latest release](https://github.com/adobe-fonts/source-sans/releases/tag/3.052R).
